export const SEARCH_TITLE_CHANGE = "SEARCH_TITLE_CHANGE";
export const GET_TITLE_FAILURE = "GET_TITLE_FAILURE";
export const GET_TITLE_SUCCESS = "GET_TITLE_SUCCESS";
export const NOM_TITLE_SUCCESS = "NOM_TITLE_SUCCESS";
